using System;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.Build.Reporting;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;
using Object=UnityEngine.Object;
namespace ReturnTide.Workshop.Editor {
 [InitializeOnLoad]public static class WorkshopV3Validation {
  static double next;static string Out=>Path.GetFullPath("EvidenceV3");
  static WorkshopV3Validation(){EditorApplication.update+=Tick;}
  public static void Run(){Directory.CreateDirectory(Out);File.WriteAllText(Path.Combine(Out,"checks.txt"),"");File.Delete(Path.Combine(Out,"COMPLETE.txt"));WorkshopBuilder.Build();var g=Object.FindObjectOfType<WorkshopGame>();Check(g.specimenPrefabs.Length==4&&g.specimenPrefabs.Select(s=>s.profile).Distinct().Count()==4,"Four separately authored models and editable profiles");Check(g.specimenPrefabs.All(s=>s.parts.Length==15),"Each family has complete independent anatomy");Check(g.hud.titleGroup.GetComponentsInChildren<UnityEngine.UI.Text>().Length==2,"Title still has only two texts");g.saveEnabled=false;SessionState.SetBool("V3.Test",true);SessionState.SetInt("V3.Step",0);EditorApplication.isPlaying=true;}
  static void Check(bool ok,string label){if(!ok)throw new Exception("V3_FAIL: "+label);Debug.Log("V3_PASS: "+label);File.AppendAllText(Path.Combine(Out,"checks.txt"),"PASS "+label+"\n");}
  static void Cut(WorkshopGame g,TissueLayer layer){g.SetTrade(false);g.cameraRig.SetView(WorkshopView.Bench,true);g.SelectTool(WorkshopTool.Scalpel);foreach(var p in g.specimen.parts.Where(p=>p.layer==layer&&!p.Removed).ToArray()){Physics.SyncTransforms();for(int i=0;i<p.cutPath.Length;i++)g.ProcessPointer(g.cameraRig.GetComponent<Camera>().WorldToScreenPoint(p.cutPath[i].position),i==0,true,false);g.ProcessPointer(Vector2.zero,false,false,true);Check(p.Removed,"Curved screen incision: "+g.specimen.profile.displayName+" / "+p.name);}}
  static void Drag(WorkshopGame g,WorkshopPart p,bool contaminate=false){g.SelectTool(WorkshopTool.Forceps);Physics.SyncTransforms();Camera c=g.cameraRig.GetComponent<Camera>();g.ProcessPointer(c.WorldToScreenPoint(p.transform.position),true,true,false);Vector3 drop=(p.toxic&&!contaminate?g.isolationTray:g.outputTray).position;drop.y=g.specimenAnchor.position.y+.82f;g.ProcessPointer(c.WorldToScreenPoint(drop),false,true,false);g.ProcessPointer(c.WorldToScreenPoint(drop),false,false,true);Check(p.Removed,"Ray-picked drag / "+p.layer+(p.toxic?" toxic":""));}
  static void FinishFish(WorkshopGame g,bool contaminate=false){if(g.specimen.IsArmored){g.SelectTool(WorkshopTool.Laser);foreach(var p in g.specimen.parts.Where(p=>p.layer==TissueLayer.Shell&&!p.Removed))p.Laser(g.balance.laserSeconds+.1f);}Cut(g,TissueLayer.Skin);Cut(g,TissueLayer.Flesh);foreach(var p in g.specimen.parts.Where(p=>p.layer==TissueLayer.Bone&&!p.Removed)){for(int i=0;i<g.specimen.profile.boneHits;i++)p.Strike();Drag(g,p);}foreach(var p in g.specimen.parts.Where(p=>p.layer==TissueLayer.Organ&&!p.Removed))Drag(g,p,contaminate);Drag(g,g.specimen.parts.First(p=>p.layer==TissueLayer.Core));}
  static void Tick(){if(!SessionState.GetBool("V3.Test",false)||!EditorApplication.isPlaying||EditorApplication.isCompiling||EditorApplication.timeSinceStartup<next)return;next=EditorApplication.timeSinceStartup+1;
   try{var g=Object.FindObjectOfType<WorkshopGame>();if(!g)return;int step=SessionState.GetInt("V3.Step",0);
    switch(step){
     case 0:Capture(g,"01-room.png");var camera=g.cameraRig.GetComponent<Camera>();Vector3 oldPosition=camera.transform.position;Quaternion oldRotation=camera.transform.rotation;g.hud.GetComponent<Canvas>().enabled=false;camera.transform.position=new Vector3(.5f,2.25f,-.3f);camera.transform.LookAt(g.researcher.headPivot.position+Vector3.up*.27f);Capture(g,"00-character-detail.png");g.hud.GetComponent<Canvas>().enabled=true;camera.transform.SetPositionAndRotation(oldPosition,oldRotation);g.Begin();break;
     case 1:Capture(g,"02-reef.png");FinishFish(g);Check(g.stockMeat==4&&g.state.purity==100,"Clean basic fish provides a meat-order batch");Check(g.DeliverOrder()&&g.state.orders==1,"Keep meat for a higher-value order");Check(!g.DeliverOrder()||g.state.orders==2,"Intact core can satisfy next order");g.SellGoods();Check(!g.SellGoods(),"No duplicate sale");Check(g.Buy(WorkshopAction.BuyLaser),"Orders fund equipment using normal earnings");Check(g.NextSpecimen(1),"Choose armored delivery");break;
     case 2:Capture(g,"03-armor.png");Check(g.specimen.CurrentLayer==TissueLayer.Shell&&g.specimen.profile.boneHits==4,"Armor has its own shell and thicker bones");FinishFish(g);g.DeliverOrder();g.SellGoods();Check(g.NextSpecimen(2),"Orders unlock venom family");break;
     case 3:Capture(g,"04-venom.png");Cut(g,TissueLayer.Skin);Cut(g,TissueLayer.Flesh);foreach(var p in g.specimen.parts.Where(p=>p.layer==TissueLayer.Bone)){for(int i=0;i<g.specimen.profile.boneHits;i++)p.Strike();Drag(g,p);}break;
     case 4:Capture(g,"05-venom-organs.png");var toxin=g.specimen.parts.First(p=>p.toxic);Check(toxin.gameObject.activeSelf,"Poison sac has visible specific anatomy");Drag(g,toxin,true);Check(g.state.purity==75,"Wrong tray contamination reduces purity");foreach(var p in g.specimen.parts.Where(p=>p.layer==TissueLayer.Organ&&!p.Removed))Drag(g,p);Drag(g,g.specimen.parts.First(p=>p.layer==TissueLayer.Core));Check(g.state.coreQualities.Last()==75&&g.stockCoreValue<g.specimen.profile.corePrice,"Damage changes actual crystal price and quality");g.SellGoods();Check(g.NextSpecimen(3),"Advanced orders unlock crystal ray");break;
     case 5:Capture(g,"06-crystal-ray.png");Check(g.specimen.profile.boneHits==2,"Fragile ray uses a different bone threshold");FinishFish(g);g.SellGoods();Check(g.Buy(WorkshopAction.BuyPeeler),"Automation competes for research materials");g.Act(WorkshopAction.BuyPeeler);Check(!g.state.peelerEnabled,"Automatic peeling can be disabled for delicate stock");g.Act(WorkshopAction.BuyPeeler);Check(g.NextSpecimen(2),"Select vulnerable fish after automation");next=EditorApplication.timeSinceStartup+2;break;
     case 6:Check(g.specimen.CurrentLayer==TissueLayer.Flesh&&g.state.purity==82,"Fast automatic peeling sacrifices delicate-fish purity");FinishFish(g);g.SellGoods();Check(g.state.orders>=3&&g.state.coins>=650,"Three stages and return are reachable without grants");g.SetTrade(true);break;
     case 7:Capture(g,"07-orders.png");Check(g.ReturnHome(),"Return requires completed orders and resources");next=EditorApplication.timeSinceStartup+4;break;
     case 8:Capture(g,"08-return.png");Check(g.hud.titleGroup.activeSelf,"Minimal ending returns to menu");SessionState.SetBool("V3.Test",false);EditorApplication.isPlaying=false;EditorApplication.delayCall+=Finish;break;
    }SessionState.SetInt("V3.Step",step+1);
   }catch(Exception e){Debug.LogException(e);SessionState.SetBool("V3.Test",false);EditorApplication.Exit(1);}}
  static void Capture(WorkshopGame g,string file){var cam=g.cameraRig.GetComponent<Camera>();var canvas=g.hud.GetComponent<Canvas>();var scaler=canvas.GetComponent<UnityEngine.UI.CanvasScaler>();var rt=new RenderTexture(1600,900,24);rt.Create();cam.targetTexture=rt;scaler.enabled=false;canvas.renderMode=RenderMode.ScreenSpaceCamera;canvas.worldCamera=cam;canvas.planeDistance=1;canvas.scaleFactor=1;Canvas.ForceUpdateCanvases();RenderPipeline.SubmitRenderRequest(cam,new UniversalRenderPipeline.SingleCameraRequest{destination=rt});var prev=RenderTexture.active;RenderTexture.active=rt;var tex=new Texture2D(1600,900,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,1600,900),0,0);tex.Apply();File.WriteAllBytes(Path.Combine(Out,file),tex.EncodeToPNG());RenderTexture.active=prev;cam.targetTexture=null;canvas.renderMode=RenderMode.ScreenSpaceOverlay;scaler.enabled=true;Object.DestroyImmediate(rt);Object.DestroyImmediate(tex);}
  static void Finish(){try{var report=BuildPipeline.BuildPlayer(new BuildPlayerOptions{scenes=new[]{WorkshopBuilder.ScenePath},locationPathName="BuildV3/ReturnTide.exe",target=BuildTarget.StandaloneWindows64,options=BuildOptions.None});Check(report.summary.result==BuildResult.Succeeded,"Windows V3 build");File.WriteAllText(Path.Combine(Out,"COMPLETE.txt"),"V3_VERIFIED");EditorApplication.Exit(0);}catch(Exception e){Debug.LogException(e);EditorApplication.Exit(1);}}
 }
}

