using System;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.Build.Reporting;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;
using Object=UnityEngine.Object;
namespace ReturnTide.Workshop.Editor {
 [InitializeOnLoad]public static class WorkshopV4Validation {
  static double next;static string Out=>Path.GetFullPath("EvidenceV4");static double recordStart,nextCapture;static int frame,actionStep;static WorkshopPart current;
  static WorkshopV4Validation(){EditorApplication.update+=Tick;}
  public static void Run(){Directory.CreateDirectory(Out);Directory.CreateDirectory(Path.Combine(Out,"Frames"));File.WriteAllText(Path.Combine(Out,"checks.txt"),"");File.WriteAllText(Path.Combine(Out,"frame-times.txt"),"");File.Delete(Path.Combine(Out,"COMPLETE.txt"));WorkshopBuilder.Build();var g=Object.FindObjectOfType<WorkshopGame>();g.saveEnabled=false;g.readHardwareInput=false;SessionState.SetInt("V4.Step",0);SessionState.SetBool("V4.Test",true);EditorApplication.isPlaying=true;}
  static void Check(bool ok,string label){if(!ok)throw new Exception("V4_FAIL: "+label);File.AppendAllText(Path.Combine(Out,"checks.txt"),"PASS "+label+"\n");Debug.Log("V4_PASS: "+label);}
  static void Cut(WorkshopGame g,WorkshopPart p){g.SelectTool(WorkshopTool.Scalpel);Physics.SyncTransforms();for(int i=0;i<p.cutPath.Length;i++)g.ProcessPointer(g.cameraRig.GetComponent<Camera>().WorldToScreenPoint(p.cutPath[i].position),i==0,true,false);g.ProcessPointer(Vector2.zero,false,false,true);Check(p.Removed,"Mouse incision still works with animated incision guide");}
  static void Drag(WorkshopGame g,WorkshopPart p){g.SelectTool(WorkshopTool.Forceps);Physics.SyncTransforms();var cam=g.cameraRig.GetComponent<Camera>();g.ProcessPointer(cam.WorldToScreenPoint(p.transform.position),true,true,false);Vector3 end=g.outputTray.position;end.y=g.specimenAnchor.position.y+.82f;g.ProcessPointer(cam.WorldToScreenPoint(end),false,true,false);g.ProcessPointer(cam.WorldToScreenPoint(end),false,false,true);Check(p.Removed,"Drag and animated deposit grant one item");}
  static void Tick(){if(!SessionState.GetBool("V4.Test",false)||!EditorApplication.isPlaying||EditorApplication.isCompiling)return;try{var g=Object.FindObjectOfType<WorkshopGame>();if(!g)return;int step=SessionState.GetInt("V4.Step",0);if(step==50){Record(g);return;}if(EditorApplication.timeSinceStartup<next)return;next=EditorApplication.timeSinceStartup+1;
   switch(step){
    case 0:Capture(g,"01-title.png");Check(g.hud.titleGroup.GetComponentsInChildren<UnityEngine.UI.Text>().Length==2,"Title remains two items");g.Begin();next=EditorApplication.timeSinceStartup+3.3;break;
    case 1:Capture(g,"02-tool-cue.png");Check(g.specimen.parts.Where(p=>p.layer==TissueLayer.Flesh).All(p=>p.gameObject.activeSelf&&!p.hitbox.enabled&&!p.Ready),"Underlying tissue is visible but cannot be harvested early");Check(g.IsToolAvailable(WorkshopTool.Scalpel)&&!g.IsToolAvailable(WorkshopTool.Hammer)&&!g.IsToolAvailable(WorkshopTool.Forceps),"Only the knife is introduced initially");Check(g.feedback.CueVisible,"Idle cue appears on the relevant tool");Check(g.hud.money.text==""&&g.hud.inventory.text==""&&g.hud.toolRow.text=="","No permanent word-plus-number HUD");var icon=g.feedback.overlay.toolIcons[0];var mesh=icon.canvasRenderer.GetMesh();File.WriteAllText(Path.Combine(Out,"icon-diagnostic.txt"),"verts="+mesh.vertexCount+" generated="+icon.GeneratedVertices+" rect="+icon.rectTransform.rect+" color="+icon.color+" renderer="+icon.canvasRenderer.GetColor()+" material="+icon.materialForRendering.name+" texture="+icon.mainTexture.name+" bounds="+mesh.bounds);Check(icon.GeneratedVertices>3&&mesh.vertexCount>3,"Native icon generates visible-sized mesh geometry");current=g.specimen.parts.First(p=>p.layer==TissueLayer.Skin);Cut(g,current);next=EditorApplication.timeSinceStartup+.25;break;
    case 2:Capture(g,"03-peel-in-motion.png");Check(!current.hitbox.enabled&&current.gameObject.activeSelf,"Peel remains visible while its collider is disabled");next=EditorApplication.timeSinceStartup+1;break;
    case 3:Capture(g,"04-gain.png");Check(g.feedback.LandingEvents==1&&g.feedback.overlay.GainEvents==1&&g.stockSkin==1,"One landing produces one transient gain without duplicate inventory");foreach(var p in g.specimen.parts.Where(p=>p.layer==TissueLayer.Skin&&!p.Removed))Cut(g,p);foreach(var p in g.specimen.parts.Where(p=>p.layer==TissueLayer.Flesh))Cut(g,p);next=EditorApplication.timeSinceStartup+1;break;
    case 4:Capture(g,"05-meat-gain.png");Check(g.IsToolAvailable(WorkshopTool.Hammer)&&!g.IsToolAvailable(WorkshopTool.Forceps),"Hammer appears at the bone layer; forceps remain undisclosed");current=g.specimen.parts.First(p=>p.layer==TissueLayer.Bone);g.SelectTool(WorkshopTool.Hammer);for(int i=0;i<g.specimen.profile.boneHits;i++)current.Strike();Check(g.IsToolAvailable(WorkshopTool.Forceps),"Breaking a rib introduces forceps");g.ProcessPointer(Vector2.zero,false,true,false);g.cameraRig.Impact(.1f);next=EditorApplication.timeSinceStartup+.1;break;
    case 5:Check(Vector3.Distance(g.cameraRig.transform.position,g.cameraRig.benchPose.position)<.0001f,"Camera stays fixed while pointer is held");g.ProcessPointer(Vector2.zero,false,false,true);Drag(g,current);g.feedback.settings.reducedMotion=true;g.cameraRig.Focus(3);next=EditorApplication.timeSinceStartup+1;break;
    case 6:Check(Mathf.Abs(g.cameraRig.GetComponent<Camera>().fieldOfView-g.cameraRig.benchFov)<.001f,"Reduced-motion mode suppresses focus zoom");g.feedback.settings.reducedMotion=false;foreach(var p in g.specimen.parts.Where(p=>p.layer==TissueLayer.Bone&&!p.Removed)){for(int i=0;i<g.specimen.profile.boneHits;i++)p.Strike();Drag(g,p);}foreach(var p in g.specimen.parts.Where(p=>p.layer==TissueLayer.Organ))Drag(g,p);next=EditorApplication.timeSinceStartup+.2;break;
    case 7:Capture(g,"06-core-reveal.png");Check(g.feedback.RevealEvents==1,"Core discovery is a distinct event");g.feedback.Surprise(g.specimen.transform.position+Vector3.up);g.feedback.Surprise(g.specimen.transform.position+Vector3.up);Check(g.feedback.SurpriseEvents==1,"Unexpected reflex is limited to once per specimen");Drag(g,g.specimen.parts.First(p=>p.layer==TissueLayer.Core));next=EditorApplication.timeSinceStartup+3;break;
    case 8:Capture(g,"07-clean-bench.png");Check(g.feedback.overlay.rewards.All(r=>!r.root.gameObject.activeSelf),"Gain popups disappear after their lifetime");Check(!g.feedback.overlay.ledger.activeSelf,"Inventory ledger stays hidden on the bench");g.SetTrade(true);next=EditorApplication.timeSinceStartup+1;break;
    case 9:Capture(g,"08-ledger.png");Check(g.feedback.overlay.ledger.activeSelf,"Trade exposes icon totals");int earned=g.GoodsValue;g.SellGoods();Check(g.state.coins==earned&&!g.SellGoods(),"Coin choreography cannot duplicate the sale");next=EditorApplication.timeSinceStartup+.5;break;
    case 10:Capture(g,"09-coin-gain.png");g.NextSpecimen(0);g.SetTrade(false);g.cameraRig.SetView(WorkshopView.Bench,true);g.state.learnedTools=1;g.feedback.settings.idleCueDelay=.9f;recordStart=EditorApplication.timeSinceStartup;nextCapture=recordStart;frame=0;actionStep=0;SessionState.SetInt("V4.Step",50);return;
   }SessionState.SetInt("V4.Step",step+1);
  }catch(Exception e){Debug.LogException(e);SessionState.SetBool("V4.Test",false);EditorApplication.Exit(1);}}
  static void Record(WorkshopGame g){double now=EditorApplication.timeSinceStartup,t=now-recordStart;float[] when={1.6f,3.0f,3.8f,4.8f,5.5f,7.0f,7.22f,7.45f,8.3f,9.7f,10.5f,11.2f};if(actionStep<when.Length&&t>=when[actionStep]){
   if(actionStep<=2)Cut(g,g.specimen.parts.First(p=>p.layer==TissueLayer.Skin&&!p.Removed));
   else if(actionStep<=4)Cut(g,g.specimen.parts.First(p=>p.layer==TissueLayer.Flesh&&!p.Removed));
   else if(actionStep<=7){g.SelectTool(WorkshopTool.Hammer);current=g.specimen.parts.First(p=>p.layer==TissueLayer.Bone&&!p.Removed);current.Strike();}
   else if(actionStep==8)Drag(g,current);
   else if(actionStep==9){foreach(var p in g.specimen.parts.Where(p=>p.layer==TissueLayer.Bone&&!p.Removed)){for(int i=0;i<g.specimen.profile.boneHits;i++)p.Strike();Drag(g,p);}}
   else if(actionStep==10){foreach(var p in g.specimen.parts.Where(p=>p.layer==TissueLayer.Organ))Drag(g,p);}
   else Drag(g,g.specimen.parts.First(p=>p.layer==TissueLayer.Core));actionStep++;}
   if(now>=nextCapture&&t<13){nextCapture=now+1.0/12;Capture(g,"Frames/frame_"+(frame++).ToString("D4")+".png",960,540);File.AppendAllText(Path.Combine(Out,"frame-times.txt"),t.ToString("F3",System.Globalization.CultureInfo.InvariantCulture)+"\n");}
   if(t>=13){g.feedback.settings.idleCueDelay=2.5f;SessionState.SetBool("V4.Test",false);EditorApplication.isPlaying=false;EditorApplication.delayCall+=Finish;}
  }
  static void Capture(WorkshopGame g,string file,int width=1600,int height=900){var cam=g.cameraRig.GetComponent<Camera>();var canvas=g.hud.GetComponent<Canvas>();var scaler=canvas.GetComponent<UnityEngine.UI.CanvasScaler>();var rt=new RenderTexture(width,height,24);rt.Create();cam.targetTexture=rt;scaler.enabled=false;canvas.renderMode=RenderMode.ScreenSpaceCamera;canvas.worldCamera=cam;canvas.planeDistance=1;canvas.scaleFactor=width/1600f;foreach(var icon in canvas.GetComponentsInChildren<WorkshopIcon>())icon.SetAllDirty();Canvas.ForceUpdateCanvases();RenderPipeline.SubmitRenderRequest(cam,new UniversalRenderPipeline.SingleCameraRequest{destination=rt});var prev=RenderTexture.active;RenderTexture.active=rt;var tex=new Texture2D(width,height,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,width,height),0,0);tex.Apply();File.WriteAllBytes(Path.Combine(Out,file),tex.EncodeToPNG());RenderTexture.active=prev;cam.targetTexture=null;canvas.renderMode=RenderMode.ScreenSpaceOverlay;scaler.enabled=true;Object.DestroyImmediate(rt);Object.DestroyImmediate(tex);}
  static void Finish(){try{var report=BuildPipeline.BuildPlayer(new BuildPlayerOptions{scenes=new[]{WorkshopBuilder.ScenePath},locationPathName="BuildV4/ReturnTide.exe",target=BuildTarget.StandaloneWindows64,options=BuildOptions.None});Check(report.summary.result==BuildResult.Succeeded,"Windows feedback build succeeds");File.WriteAllText(Path.Combine(Out,"COMPLETE.txt"),"V4_VERIFIED");EditorApplication.Exit(0);}catch(Exception e){Debug.LogException(e);EditorApplication.Exit(1);}}
 }
}



