using System;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.Build.Reporting;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;
using Object=UnityEngine.Object;
namespace ReturnTide.Workshop.Editor {
 [InitializeOnLoad]
 public static class WorkshopValidation {
  static double next;static string Output=>Path.GetFullPath("EvidenceV2");
  static WorkshopValidation(){EditorApplication.update+=Tick;}
  public static void Run(){Directory.CreateDirectory(Output);File.WriteAllText(Path.Combine(Output,"checks.txt"),"");File.Delete(Path.Combine(Output,"COMPLETE.txt"));WorkshopBuilder.Build();var game=Object.FindObjectOfType<WorkshopGame>();Check(game.hud.titleGroup.GetComponentsInChildren<UnityEngine.UI.Text>().Length==2,"Title has exactly two texts: title and start");Check(game.specimen.parts.Length==15,"Fifteen separately editable anatomy parts");Check(game.cameraRig.benchPose&&game.researcher.headPivot,"Camera poses and articulated character are serialized");game.saveEnabled=false;SessionState.SetBool("Workshop.Test",true);SessionState.SetInt("Workshop.Step",0);EditorApplication.isPlaying=true;}
  static void Check(bool condition,string label){if(!condition)throw new Exception("WORKSHOP_FAIL: "+label);File.AppendAllText(Path.Combine(Output,"checks.txt"),"PASS "+label+"\n");Debug.Log("WORKSHOP_PASS: "+label);}
  static void Cut(WorkshopSpecimen s,TissueLayer layer){s.game.SetTrade(false);s.game.cameraRig.SetView(WorkshopView.Bench,true);s.game.SelectTool(WorkshopTool.Scalpel);foreach(var p in s.parts.Where(p=>p.layer==layer&&!p.Removed).ToArray()){Physics.SyncTransforms();for(int i=0;i<p.cutPath.Length;i++){Vector3 screen=s.game.cameraRig.GetComponent<Camera>().WorldToScreenPoint(p.cutPath[i].position);s.game.ProcessPointer(screen,i==0,true,false);}s.game.ProcessPointer(Vector2.zero,false,false,true);Check(p.Removed,"Mouse ray and traced screen path remove "+p.layer);}}
  static void Drag(WorkshopGame g,WorkshopPart p){g.SelectTool(WorkshopTool.Forceps);Physics.SyncTransforms();var camera=g.cameraRig.GetComponent<Camera>();g.ProcessPointer(camera.WorldToScreenPoint(p.transform.position),true,true,false);Vector3 drop=g.outputTray.position;drop.y=g.specimenAnchor.position.y+.82f;g.ProcessPointer(camera.WorldToScreenPoint(drop),false,true,false);g.ProcessPointer(camera.WorldToScreenPoint(drop),false,false,true);Check(p.Removed,"Screen drag deposits "+p.layer+" in tray");}
  static void FinishFish(WorkshopGame g){foreach(var shell in g.specimen.parts.Where(p=>p.layer==TissueLayer.Shell&&p.gameObject.activeSelf))shell.Laser(g.balance.laserSeconds+.1f);Cut(g.specimen,TissueLayer.Skin);Cut(g.specimen,TissueLayer.Flesh);foreach(var bone in g.specimen.parts.Where(p=>p.layer==TissueLayer.Bone)){for(int i=0;i<g.balance.boneHits;i++)bone.Strike();bone.Complete();}foreach(var organ in g.specimen.parts.Where(p=>p.layer==TissueLayer.Organ))organ.Complete();g.specimen.parts.First(p=>p.layer==TissueLayer.Core).Complete();}
  static void Tick(){
   if(!SessionState.GetBool("Workshop.Test",false)||!EditorApplication.isPlaying||EditorApplication.isCompiling||EditorApplication.timeSinceStartup<next)return;
   next=EditorApplication.timeSinceStartup+1;
   try{
    var g=Object.FindObjectOfType<WorkshopGame>();if(!g)return;int step=SessionState.GetInt("Workshop.Step",0);
    switch(step){
     case 0:Capture(g,"01-title.png");Check(!g.state.everSold&&g.stockCores==0,"Fresh run has no inventory or economy clutter");g.Begin();break;
     case 1:Capture(g,"02-bench.png");Check(g.specimen.CurrentLayer==TissueLayer.Skin,"Soft fish starts with skin");var part=g.specimen.parts.First(p=>p.layer==TissueLayer.Skin);part.Trace(Vector3.one*999);Check(part.CutIndex==0,"Holding away from incision does not cut");part.Trace(part.cutPath[0].position);part.ResetTrace();Check(part.CutIndex==0,"Interrupted incision resets");Cut(g.specimen,TissueLayer.Skin);Check(g.stockSkin==3&&g.specimen.CurrentLayer==TissueLayer.Flesh,"Trace all skin paths to reveal muscle");break;
     case 2:Capture(g,"03-muscle.png");Cut(g.specimen,TissueLayer.Flesh);Check(g.stockMeat==2&&g.specimen.CurrentLayer==TissueLayer.Bone,"Muscle dissection exposes three ribs");break;
     case 3:Capture(g,"04-ribs.png");foreach(var bone in g.specimen.parts.Where(p=>p.layer==TissueLayer.Bone)){Check(!bone.CanDrag(WorkshopTool.Forceps),"Intact bone cannot be lifted");for(int i=0;i<g.balance.boneHits;i++)bone.Strike();Check(bone.CanDrag(WorkshopTool.Forceps)&&!bone.CanDrag(WorkshopTool.Scalpel),"Broken bone requires forceps");Drag(g,bone);}break;
     case 4:Capture(g,"05-organs.png");Check(!g.specimen.parts.First(p=>p.layer==TissueLayer.Core).gameObject.activeSelf,"Core remains hidden until search");foreach(var organ in g.specimen.parts.Where(p=>p.layer==TissueLayer.Organ))organ.Complete();break;
     case 5:Capture(g,"06-crystal.png");Check(g.specimen.parts.First(p=>p.layer==TissueLayer.Core).gameObject.activeSelf,"Searching the correct organ reveals the core");Drag(g,g.specimen.parts.First(p=>p.layer==TissueLayer.Core));Check(g.specimenComplete&&g.stockCores==1&&g.state.parts==3,"Core and mutation materials are harvested");Check(!g.Buy(WorkshopAction.BuyLaser),"Cannot purchase without money");g.SetTrade(true);break;
     case 6:Capture(g,"07-trade.png");Check(g.SellGoods()&&g.state.coins==136,"Fish products sell for configured prices");Check(!g.SellGoods(),"Repeated sale cannot duplicate money");Check(g.NextSpecimen()&&g.specimen.IsArmored,"Second arrival has an exoskeleton");Check(!g.specimen.parts.First(p=>p.layer==TissueLayer.Core).gameObject.activeSelf,"Armor blocks crystal access");int coins=g.state.coins;Check(g.NextSpecimen()&&g.state.coins==coins+12,"Unaffordable armored fish can be returned");FinishFish(g);g.SellGoods();Check(g.Buy(WorkshopAction.BuyLaser)&&g.state.laser,"Sales and mutation materials unlock laser");Check(!g.Buy(WorkshopAction.BuyLaser),"Owned tool cannot be purchased twice");g.SetTrade(false);break;
     case 7:Check(g.NextSpecimen()&&g.specimen.variant==2,"Tentacled mutation enters sequence");FinishFish(g);g.SellGoods();g.NextSpecimen();FinishFish(g);g.SellGoods();g.NextSpecimen();Check(g.specimen.variant==3&&g.specimen.goldenCrown.activeSelf,"Golden easter egg fish appears");break;
     case 8:Capture(g,"08-easter-egg.png");FinishFish(g);Check(g.stockCoreValue==g.balance.coreValue*5,"Rare core has greater sale value");g.SellGoods();Check(g.Buy(WorkshopAction.BuyPeeler),"Peeler purchases consume money and materials");g.NextSpecimen();next=EditorApplication.timeSinceStartup+2;break;
     case 9:Check(g.specimen.CurrentLayer==TissueLayer.Flesh,"Peeler automates skin removal on next fish");var restored=JsonUtility.FromJson<WorkshopSave>(JsonUtility.ToJson(g.state));Check(restored.laser&&restored.peeler&&restored.removed.Count==3,"Save data retains tools and current dissection progress");FinishFish(g);g.SellGoods();g.NextSpecimen();Check(g.specimen.IsArmored,"Armored fish reappears after upgrades");g.SelectTool(WorkshopTool.Laser);break;
     case 10:Capture(g,"09-armored.png");foreach(var shell in g.specimen.parts.Where(p=>p.layer==TissueLayer.Shell))shell.Laser(g.balance.laserSeconds+.1f);Check(g.specimen.CurrentLayer==TissueLayer.Skin,"Laser actually opens the shell");next=EditorApplication.timeSinceStartup+2;break;
     case 11:FinishFish(g);g.SellGoods();Check(g.state.coins>=g.balance.returnPrice&&g.state.parts>=g.balance.returnParts,"Return is reachable through normal earnings");Check(g.ReturnHome(),"Repairing signal starts return sequence");next=EditorApplication.timeSinceStartup+4;break;
     case 12:Capture(g,"10-return.png");Check(g.hud.titleGroup.activeSelf,"Return ends at a minimal two-item menu");SessionState.SetBool("Workshop.Test",false);EditorApplication.isPlaying=false;EditorApplication.delayCall+=Finish;break;
    }
    SessionState.SetInt("Workshop.Step",step+1);
   }catch(Exception ex){Debug.LogException(ex);SessionState.SetBool("Workshop.Test",false);EditorApplication.Exit(1);}
  }
  static void Capture(WorkshopGame g,string file){var cam=g.cameraRig.GetComponent<Camera>();var canvas=g.hud.GetComponent<Canvas>();var scaler=canvas.GetComponent<UnityEngine.UI.CanvasScaler>();var rt=new RenderTexture(1600,900,24,RenderTextureFormat.ARGB32);rt.Create();cam.targetTexture=rt;scaler.enabled=false;canvas.renderMode=RenderMode.ScreenSpaceCamera;canvas.worldCamera=cam;canvas.planeDistance=1;canvas.scaleFactor=1;Canvas.ForceUpdateCanvases();var request=new UniversalRenderPipeline.SingleCameraRequest{destination=rt};RenderPipeline.SubmitRenderRequest(cam,request);var prev=RenderTexture.active;RenderTexture.active=rt;var tex=new Texture2D(1600,900,TextureFormat.RGB24,false);tex.ReadPixels(new Rect(0,0,1600,900),0,0);tex.Apply();File.WriteAllBytes(Path.Combine(Output,file),tex.EncodeToPNG());RenderTexture.active=prev;cam.targetTexture=null;canvas.renderMode=RenderMode.ScreenSpaceOverlay;scaler.enabled=true;Object.DestroyImmediate(rt);Object.DestroyImmediate(tex);}
  static void Finish(){try{var report=BuildPipeline.BuildPlayer(new BuildPlayerOptions{scenes=new[]{WorkshopBuilder.ScenePath},locationPathName="BuildV2/ReturnTide.exe",target=BuildTarget.StandaloneWindows64,options=BuildOptions.None});Check(report.summary.result==BuildResult.Succeeded,"Windows workshop build succeeds");File.WriteAllText(Path.Combine(Output,"COMPLETE.txt"),"WORKSHOP_V2_VERIFIED");EditorApplication.Exit(0);}catch(Exception ex){Debug.LogException(ex);EditorApplication.Exit(1);}}
 }
}

